### ISSUE TITLE
Ability to define multiple endpoins

### ISSUE THREAD

**Issue by kevgo** [Originate/psapi#14]
This might already work, but there is no feature spec for it.

> As a developer mocking a complex API with several endpoints
I want to be able to define multiple endpoints through a single Psapi configuration
So that my mock API exposes the same set of endpoints as my real server.

**Comment by ssebelius** [comment]
:+1:

**Comment by alexpeachey** [comment]
Yes, this is already there, that's why the config is an array. While there is no specific feature spec showing it works to have two endpoints defined, by being an array of one and working it implicitly implies it should work for however many you put in the array.

For thoroughness we could add a feature spec showing the array can hold two items, but really an array of 1 acts the same as an array of 2, 3, etc.
